name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@treeunfe"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Test
        run: npm test

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting semantic release..."
          echo "Current branch: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"

          # Run semantic-release with debug
          npx semantic-release --debug

          echo "Semantic release completed!"

      - name: Clean up temporary files
        run: |
          echo "Cleaning up temporary files..."
          rm -rf .release/
          rm -f *.tgz
          echo "Cleanup completed!"
