name: Simple Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

env:
  NODE_VERSION: '22'
  NPM_REGISTRY: 'https://npm.pkg.github.com'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: ${{ env.NPM_REGISTRY }}
          scope: '@treeunfe'

      - name: Install dependencies
        run: npm ci

      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            TAG_NAME="${{ github.ref_name }}"
            VERSION=${TAG_NAME#v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Update package.json version
        run: npm version ${{ steps.version.outputs.version }} --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Test package
        run: npm test

      - name: Generate changelog
        id: changelog
        run: |
          # Install conventional-changelog-cli
          npm install -g conventional-changelog-cli
          
          # Generate changelog
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0 > temp_changelog.md
          
          # Create new changelog entry
          NEW_VERSION="${{ steps.version.outputs.version }}"
          TODAY=$(date +%Y-%m-%d)
          
          echo "# Changelog" > new_changelog.md
          echo "" >> new_changelog.md
          echo "## [$NEW_VERSION] - $TODAY" >> new_changelog.md
          echo "" >> new_changelog.md
          
          # Get commits since last tag
          if git describe --tags --abbrev=0 >/dev/null 2>&1; then
            LAST_TAG=$(git describe --tags --abbrev=0)
            echo "### Changes since $LAST_TAG" >> new_changelog.md
            echo "" >> new_changelog.md
            
            # Get conventional commits
            git log --pretty=format:"%s" $LAST_TAG..HEAD | grep -E "^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?:" | head -20 >> new_changelog.md
          else
            echo "### Initial Release" >> new_changelog.md
            echo "" >> new_changelog.md
          fi
          
          echo "" >> new_changelog.md
          cat CHANGELOG.md >> new_changelog.md
          mv new_changelog.md CHANGELOG.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json CHANGELOG.md
          git commit -m "chore(release): ${{ steps.version.outputs.version }}"
          git push origin HEAD:${{ github.ref_name }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Release ${{ steps.version.outputs.version }}" \
            --notes "$(cat CHANGELOG.md | head -50)" \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
